package com.plsql.tools.templates;

@Deprecated
public class Templates {
    public static final String CLASS_TEMPLATE = """
            package <PACKAGE_NAME>;
                        
            import com.plsql.tools.DataSourceProvider;
            import oracle.jdbc.OracleTypes;
                        
            import javax.sql.DataSource;
            import java.sql.CallableStatement;
            import java.sql.Connection;
            import java.sql.ResultSet;
            import java.sql.SQLException;
            import java.sql.JDBCType;
                        
            import com.plsql.tools.gen.tools.DateTools;
            import com.plsql.tools.gen.tools.StringTools;
            import com.plsql.tools.exceptions.PlsqlException;
                        
            /**
             * ----------------------------------------------------------------------------
             * THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY
             * ----------------------------------------------------------------------------
             * This class was automatically generated by a code generation tool.
             * Any modifications to this file may be overwritten when the code is regenerated.
             *
             * ----------------------------------------------------------------------------
             */
            public class <CLASS_NAME> extends <EXTENDED_CLASS_NAME> {
                        
                public <CLASS_NAME>(DataSourceProvider dataSourceProvider) {
                    super(dataSourceProvider);
                }
                
                <METHODS:{method | <method>
                }>

            }
            """;
}
