package com.plsql.tools.processor;

public class Templates {
    public static final String CLASS_TEMPLATE = """
            package <packageName>;
            
            import com.plsql.tools.DataSourceProvider;
            import oracle.jdbc.OracleTypes;
                        
            import javax.sql.DataSource;
            import java.sql.CallableStatement;
            import java.sql.Connection;
            import java.sql.ResultSet;
            import java.sql.SQLException;
            /**
             * ----------------------------------------------------------------------------
             * THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY
             * ----------------------------------------------------------------------------
             * This class was automatically generated by a code generation tool.
             * Any modifications to this file may be overwritten when the code is regenerated.
             *
             * ----------------------------------------------------------------------------
             */
            public class <className> extends <extendedClassName> {
            
                public <className>(DataSourceProvider dataSourceProvider) {
                    super(dataSourceProvider);
                }
                
                <methods:{method |  <method>
                }>

            }
            """;
    public static final String METHOD_TEMPLATE = """
            <statementStaticCall>
            
            @Override
            public <returnType> <methodName>(<parameters>){
                DataSource ds = dataSourceProvider.getDataSource("<dataSource>");
                try (Connection cnx = ds.getConnection();
                     CallableStatement stmt = cnx.prepareCall(<procedureFullName>)
                ) {
                    int pos = 1;
                    <statementPopulation:{statement |  <statement>
                    }>
                    stmt.execute();
                    var rest = (ResultSet) stmt.getObject(pos);
                    while (rest.next()) {
                        System.out.println(rest.next());
                    }
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
            """;
}
