package com.plsql.tools.templates;

public enum ResultSetTemplateParams {
    INIT_LIST_STATEMENT,
    POSITION,
    OBJECT_INIT_STATEMENT,
    ADD_TO_LIST,
    STMT_RESULT_TYPE,
    RETURN_STATEMENT,
    STMT_GETTER,
    HANDLE_EMPTY_STATEMENT,
    WRAPPER_INIT_STATEMENT,
    ADD_OBJECT_STATEMENT,
    SETTER_STATEMENTS;
}
