package com.plsql.tools.templates;


// TODO: DECOMPOSE TO MULTIPLE ENUMS
public enum TemplateParams {
    PACKAGE_NAME,
    CLASS_NAME,
    EXTENDED_CLASS_NAME,
    RETURN_TYPE,
    RETURN_STATEMENT,
    METHOD_NAME,
    METHODS,
    PARAMETERS,
    PROCEDURE_FULL_NAME,
    PROCEDURE_CALL_NAME,
    PACKAGE_CALL_NAME,
    PROCEDURE_PARAMETERS,

    STATEMENT_STATIC_CALL,
    DATA_SOURCE,
    STATEMENT_POPULATION,
    REGISTER_OUT_PARAM,
    OUT_STATEMENTS,
    INIT_POS,
    RESULT_SET_EXTRACTION,
    SUCCESS_RETURN
}
