package com.plsql.tools.templates;

public class Templates {
    public static final String CLASS_TEMPLATE = """
            package <PACKAGE_NAME>;
                        
            import com.plsql.tools.DataSourceProvider;
            import oracle.jdbc.OracleTypes;
                        
            import javax.sql.DataSource;
            import java.sql.CallableStatement;
            import java.sql.Connection;
            import java.sql.ResultSet;
            import java.sql.SQLException;
            import java.sql.JDBCType;
            
            import com.plsql.tools.gen.tools.DateTools;
            
            /**
             * ----------------------------------------------------------------------------
             * THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY
             * ----------------------------------------------------------------------------
             * This class was automatically generated by a code generation tool.
             * Any modifications to this file may be overwritten when the code is regenerated.
             *
             * ----------------------------------------------------------------------------
             */
            public class <CLASS_NAME> extends <EXTENDED_CLASS_NAME> {
                        
                public <CLASS_NAME>(DataSourceProvider dataSourceProvider) {
                    super(dataSourceProvider);
                }
                
                <METHODS:{method |  <method>
                }>

            }
            """;
    public static final String PROCEDURE_METHOD_TEMPLATE = """
            <STATEMENT_STATIC_CALL>
            @Override
            public <RETURN_TYPE> <METHOD_NAME>(<PARAMETERS>){
                DataSource ds = dataSourceProvider.getDataSource("<DATA_SOURCE>");
                try (Connection cnx = ds.getConnection();
                     CallableStatement stmt = cnx.prepareCall(<PROCEDURE_FULL_NAME>)
                ) {
                    <INIT_POS>
                    <STATEMENT_POPULATION>
                    <REGISTER_OUT_PARAM>
                    stmt.execute();
                    <RESULT_SET_EXTRACTION>
                    <RETURN_STATEMENT>
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
            """;

    public static final String FUNCTION_METHOD_TEMPLATE = """
            <STATEMENT_STATIC_CALL>
            @Override
            public <RETURN_TYPE> <METHOD_NAME>(<PARAMETERS>){
                DataSource ds = dataSourceProvider.getDataSource("<DATA_SOURCE>");
                try (Connection cnx = ds.getConnection();
                     CallableStatement stmt = cnx.prepareCall(<PROCEDURE_FULL_NAME>)
                ) {
                    <INIT_POS>
                    <REGISTER_OUT_PARAM>
                    <STATEMENT_POPULATION>
                    stmt.execute();
                    <RESULT_SET_EXTRACTION>
                    <RETURN_STATEMENT>
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
            """;

}
